[package]
name = "hylo_communities"
version = "0.0.3"
authors = ["Philip Beadle <philip.beadle@live.com.au>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
hdk = "0.0.40-alpha1"
holochain_json_derive = "=0.0.17"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
